spring:
  application:
    name: books-api
  datasource:
    url: jdbc:mysql://localhost:3306/books_api
    username: root
    password: 1VQEpYC7[8,j#?Jk
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update #Define que o Hibernate deve criar as tabelas automaticamente
  sql:
    init:
      #Define que os scripts de inicializa��o do banco de dados devem ser executados sempre
      mode: always

  data:
    redis:
        host: localhost
        port: 6379
        timeout: 5000ms
